SettimanaFlessibile/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app.urls')),
]

app/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.urls import path

urlpatterns = [
    url(r'^$', views.home),
    url(r'^corsi/$', views.corsi),
    url(r'^mieicorsi/$', views.miei_corsi),
    path(r'iscriviti/<idcorso>', views.iscrizione),
    url(r'^home/$', views.home),
    url(r'^login/$', views.login_page),
    path(r'dettagli/<idcorso>', views.dettagli),
    path(r'giorni/<giorno>', views.filtra_giorni),
    path(r'informazioni/', views.informazioni),
    path(r'categorie/<categoria>', views.filtra_categorie),
    url(r'^creacorso/$', views.create_corso),
    url(r'^logout/$', views.logout_view),
    path(r'success/<idcorso>', views.success_view),
    path(r'rimuovi/<idcorso>', views.rimuovi_iscrizione),
    path(r'rimuovicorso/<idcorso>', views.rimuovi_corso),
    path(r'appello/<idcorso>', views.appello),
    path(r'accetta/<idapprovazione>', views.accetta_corso),
    url(r'^newuser/$', views.create_user),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.serializers.json import DjangoJSONEncoder
from django.core.validators import MaxValueValidator, MinValueValidator


class Aula(models.Model):

    nome_aula = models.CharField(
        max_length=100,
        choices=([
            ('Palestra', 'Palestra'),
            ('Aula Normale', 'Aula Normale'),
            ('Aula Magna', 'Aula Magna'),
            ('Laboratorio di informatica', 'Laboratorio di informatica'),
        ]),
    )
    capacita = models.IntegerField(default=30)

    def __str__(self):
        return self.nome_aula

class Giorno(models.Model):

    giorno_della_settimana = models.CharField(
        max_length=80,
        choices=([
            ('Lunedì', 'Lunedì'),
            ('Martedì', 'Martedì'),
            ('Mercoledì', 'Mercoledì'),
            ('Giovedì', 'Giovedì'),
            ('Venerdì', 'Venerdì'),
        ]),
        default='Lunedì'
    )

    def __str__(self):
        return self.giorno_della_settimana


class Fascia(models.Model):

    giorno = models.ForeignKey('Giorno', on_delete=models.CASCADE)
    fascia = models.CharField(
        max_length=80,
        choices=([
            ('Prima Fascia', 'Prima Fascia'),
            ('Seconda Fascia', 'Seconda Fascia'),
            ('Terza Fascia', 'Terza Fascia'),
        ]),
        default='Prima Fascia'
    )

    def __str__(self):
        return self.giorno.giorno_della_settimana + ', ' + self.fascia

class Categoria(models.Model):

    nome = models.CharField(max_length=150)

    def __str__(self):
        return self.nome

class Corso(models.Model):

    nome = models.CharField(max_length=100)
    descrizione = models.TextField(max_length=1500)
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE, null=True, blank=True)

    is_progressive = models.BooleanField(default=True)
    fasce = models.ManyToManyField('Fascia')

    aula = models.ForeignKey('Aula', on_delete=models.CASCADE, related_name='aula')

    creatore = models.ForeignKey('Utente', on_delete=models.CASCADE, related_name='creatore')
    ospitanti = models.ManyToManyField('Utente')

    iscritti = models.ManyToManyField('Utente', related_name='iscritti')
    full = models.BooleanField(default=False)

    convalidato = models.BooleanField(default=False)

    def is_creator(self, studente):
        if studente == self.creatore:
            return True
        return False

    def __str__(self):
        return self.nome

    def contains_studente(self, studente):
        std = self.iscritti.filter(user=studente).count()
        if std < 1:
            return False
        return True

class Approvazione(models.Model):

    corso = models.ForeignKey('Corso', on_delete=models.CASCADE)
    studente = models.ForeignKey('Utente', on_delete=models.CASCADE)

    approva = models.BooleanField(default=False)

    def __str__(self):
        return self.corso.nome



class Utente(models.Model):

    nome = models.CharField(max_length=150)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    classe = models.IntegerField(default=1,validators=[MaxValueValidator(5), MinValueValidator(1)])
    sezione = models.CharField(max_length=1)

    iscrizioni = models.ManyToManyField('Corso', related_name='iscrizioni')
    hosted_courses = models.ManyToManyField('Corso')

    def is_hosted_course(self, corso):
        corsi = self.hosted_courses.filter(pk=corso.id)
        if corsi.count() == 0:
            return False
        return True

    def is_fascia_taken(self, fascia_to_check):
        iscrizione = self.iscrizioni.filter(fasce__fascia=fascia_to_check.fascia).filter(fasce__giorno=fascia_to_check.giorno).count()
        if iscrizione > 0:
            return True
        return False

    def __str__(self):
        return self.nome

app/templates/corsi/appelli.html
{% extends 'base.html' %}

{% block content %}

<table class="table">
  <thead>
    <tr>
      <th>nome</th><th>classe</th>
    </tr>
  </thead>
  <<tbody>
    {% for studente in iscritti %}
      <tr>
        <td>{{studente.nome}}</td><td><center>{{studente.classe}}{{studente.sezione}}</center></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

app/templates/corsi/corsi.html
{% extends 'base.html' %}


{% block head %}
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/base-min.css">
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-min.css">
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
{% endblock %}


{% block content %}

<h3>Tutti i corsi:</h3> <br>
<div class="line"></div>
{% for corso in corsi %}

  <div class="pure-g">
    <div class="pure-u-md-1-2 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-5 centered-text"><p>titolo: {{ corso.nome }}</p></div>
    <div class="pure-u-md-1-2 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-5 centered-text"><p>categoria: {{corso.categoria}}</p></div>
    <div class="pure-u-md-1-3 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-3 pure-u-xl-1-5 centered-text"><p>aula: {{corso.aula.nome_aula}}</p></div>
    {% if corso.progressivo == True %}
      <div class="pure-u-md-1-3 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-3 pure-u-xl-1-5 centered-text"><p>progressivo</p></div>
    {% else %}
      <div class="pure-u-md-1-3 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-3 pure-u-xl-1-5 centered-text"><p>singolo</p></div>
    {% endif %}
    <div class="pure-u-md-1-3 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-3 pure-u-xl-1-5 centered-text"><p>
      <button class="btn btn-primary"><a href='/iscriviti/{{corso.id}}'>Vedi dettagli</a></button>
    </p></div>
    <div class="line"></div>
  </div>

{% endfor %}


<script type="text/javascript">
$(document).ready(function () {
    $('#tutticorsi').toggleClass('active')
    $('#homelink').toggleClass('active')
});
</script>
<script>
$(document).ready(function () {
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
    });
});
</script>


{% endblock %}

app/templates/corsi/crea_corso.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

  <h1>Crea un corso</h1>
  <p><bold>Come creare un corso</bold>:<br> Specifica titolo, descrizione, categoria e aula del corso, oltre al tipo di corso (progressivo o no).<br>
    Specifica poi gli utenti (mettendo il loro nome utente e la loro classe) che ospiteranno il corso. (in caso sei da solo devi mettere il tuo nome, altrimenti è facoltativo)</p>

  <div class="line"></div>
  <div id="error"></div>

  <div class="myform form-group">
    <small id="passwordHelpBlock" class="form-text text-muted">
      Non sono ammessi caratteri speciali come emoji nei titoli dei corsi o nelle descrizioni
    </small>
    <br>
    {{ crea_corso_form.as_p }}

    {% for fascia in fasce %}
      <input type="button" value="{{fascia}}" class="fasciabutton btn btn-secondary" onclick="aggiungi_fascia(this)">
    {% endfor %}

    <div class="line"></div>

    <div class="aggiungiospitantiform">
      <div class="ospitanti"></div>
      <div class="container">
        nome: <input type="text" id="ospitanti" placeholder="nome cognome"><br>
        classe: <input type="text" id="classedellospitante" placeholder="classe"><br><br>
        <button id="aggiungiospitante" onclick="aggiungi_studente()" class="btn btn-info">Aggiungi</button>
        <small id="ospitiHelpBlock" class="form-text text-muted">
          inserisci nome, cognome e classe (es: mariorossi 1a) degli studenti che terranno il corso.
        </small>
      </div>
    </div>

    <div class="line"></div>

    <p>Nota: premendo questo bottone verrà creato il corso</p>
    <button onclick="crea_corso(this)" class="btn btn-primary">Crea</button>
  </div>

</div>

<script>
var aula = ""
var fascia = []
var studenti_referenti = []
var classi = []
var categoria = ""

$(document).ready(function () {
  $('#creacorso').toggleClass('active')
  $('#homelink').toggleClass('active')
  $('#id_aula').on('change',function(){
    aula= $("#id_aula option:selected").text();
  });
  $('#id_categoria').on('change', function() {
    categoria = $("#id_categoria option:selected").text();
  })
})

function toogle_fascia(str) {
  if (fascia.includes(str)) {
    var index = fascia.indexOf(str);
    if (index > -1) {fascia.splice(index, 1);}
  } else {fascia.push(str)}
}
function aggiungi_fascia(nome_fascia) {
  var x = nome_fascia;
  x.classList.toggle('btn-info');
  x.classList.toggle('btn-secondary');
  var new_button = x.parentNode.replaceChild(x, nome_fascia);
  toogle_fascia(x.value)
}

function getCookie(name) {var cookieValue = null;if (document.cookie && document.cookie != '') {var cookies = document.cookie.split(';');
       for (var i = 0; i < cookies.length; i++) {var cookie = jQuery.trim(cookies[i]);if (cookie.substring(0, name.length + 1) == (name + '=')) {
         cookieValue =   decodeURIComponent(cookie.substring(name.length + 1));break;}}}return cookieValue;}
 var csrftoken = getCookie('csrftoken');function csrfSafeMethod(method) {return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));}

//studenti referenti
function validate_studente(n, c) {
  //temporary, waiting implementation
  return true
}
function aggiungi_studente() {
  var nome_cognome = $('#ospitanti').val();
  nome_cognome = nome_cognome.replace(/\s+/g, '').toLowerCase();
  var classe = $('#classedellospitante').val();
  classe = classe.replace(/\s+/g, '').toLowerCase();
  if (nome_cognome == "") {
    $('#error').html('specifica il nome e il cognome');
    return
  }
  if (classe == ""){
    $('#error').html('specifica la classe dello studente');
    return
  }
  if (validate_studente(nome_cognome, classe) == true) {
    var button = '<button class="btn btn-primary"onclick="rimuovi_studente(this)">Rimuovi</button>';
    var text = `<div class="studenti"><span>${nome_cognome}</span>, <span>${classe}</span>. ${button}</div<br>`;
    $('.ospitanti').append(text);
    studenti_referenti.push(nome_cognome);
    classi.push(classe);
  }
}
function rimuovi_studente(studente) {
  studenti_referenti.splice(studenti_referenti.indexOf(studente.parentNode.firstChild.innerHTML), 1);
  studente.parentNode.parentNode.removeChild(studente.parentNode);
  classi.splice(classi.indexOf(studente.parentNode.children[1].innerHTML), 1);
}

function validate_data(titolo, descrizione, p, a, fasce, ospiti, classi) {
  if (titolo == "" || titolo == " ") {
    $('#error').html('Per favore specifica un titolo')
    return false}
  if (descrizione == "" || descrizione == " ") {
    $('#error').html('Per favore specifica una descrizione')
    return false}
  if (a == "" || a == " " || a == "---------") {
    $('#error').html("Per favore specifica un'aula")
    return false
  }
  if (categoria == "---------" || categoria == "" || categoria == " ") {
    $('#error').html("Per favore specifica almeno una categoria")
    return false
  }
  if (ospiti.length != classi.length) {
    $('#error').html('Per favore immetti i nomi di tutti gli studenti con le relative classi')
    return false
  }
  for (var counter in classi) {
    if (classi[counter].length != 2) {
      $('#error').html('ricordati di specificare tutte le classi, nel formato: classe sezione. esempio: 3b, 5c, 1f')
      return false
    }
  }
  if (fasce.length == 0) {
    $('#error').html('ricordati di specificare almeno una fascia')
    return false
  }

  return true
}

function crea_corso(crea_btn) {
  crea_btn.innerHTML = 'Creando il corso...';

  var titolo = $('#id_nome').val();
  var descrizione = $('#id_descrizione').val();
  var progressivo = $('#id_is_progressive').is(':checked');
  var a = aula
  var fasce = fascia;
  var ospiti = studenti_referenti;

  if (validate_data(titolo, descrizione, progressivo, a, fasce, ospiti, classi) == false) {
    $('#error').addClass('alert')
    $('#error').addClass('alert-danger')
    crea_btn.innerHTML = 'crea';
    return;
  }

  var csrftoken = getCookie('csrftoken');
  $.ajax({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    },
    url: '/creacorso/',
    data: {
      'titolo': titolo,
      'descrizione': descrizione,
      'is_progressive': progressivo,
      'categoria': categoria,
      'aula': a,
      'fasce[]': fasce,
      'ospiti[]': ospiti,
      'classi[]': classi,
    },
    method: 'POST',
    datatype: 'json',
    success: function(r_d) {
      if (r_d['success']) {
        window.location.replace("/");crea_btn.innerHTML = 'crea';}
      else {
        $('#error').addClass('alert')
        $('#error').addClass('alert-danger')
        crea_btn.innerHTML = 'crea';
        $('#error').html(r_d['error'])
      }
    }
});

}
</script>

{% endblock %}

app/templates/corsi/dettagli.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="line"></div>
  Titolo: <h3>{{ corso.nome }}</h3><br>
  descrizione: {{ corso.descrizione }}<br>
  categoria: {{ corso.categoria }}<br>
  {% if corso.convalidato %}
    stato: convalidato
  {% else %}
    stato: non convalidato
  {% endif %}
  <br>
  {% if corso.full %}
    pieno: si
  {% else %}
    pieno: no
  {% endif %}
  <br>
  {% if corso.is_progressive %}
    tipologia: singolo
  {% else %}
    tipologia: progressivo
  {% endif %}
  <div class="line"></div>
  fasce:
  {% for fascia in fasce %}
    <p>{{fascia}} </p>
  {% endfor %}
  <div class="line"></div>
  creatore: <p>{{ corso.creatore }}, {{ corso.creatore.classe }}{{ corso.creatore.sezione }}</p>
  <br>
  studenti referenti:
  {% for studente in studenti %}
    <p>{{studente}}, {{studente.classe}}{{studente.sezione}}</p>
  {% endfor %}
  <br>
  iscritti: {{iscritti}}/{{corso.aula.capacita}}
  <br>
  <br>
  <button class="btn btn-info"><a href="/appello/{{corso.id}}">Appello</a></button>




</div>



{% endblock %}

app/templates/corsi/home.html
{% extends "base.html" %}


{% block content %}

<div class="messages">

<!--qua vanno i messaggi del tipo: corso creato con successo-->
</div>
<script>
$(document).ready(function () {
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
    });
});
</script>

Ciao! Iscriviti o crea un corso
<br>

Approvazioni: <br>
{% for approvazione in approvazioni %}
  {{approvazione}}
  <button class="btn btn-primary"><a href="accetta/{{approvazione.id}}">Accetta</a></button><br>
  <div class="line"></div>
{% endfor %}

{% endblock %}

app/templates/corsi/informazioni.html
{% extends 'base.html' %}


{% block content %}
<h3>Come usare questo sito</h3>
filler text filler text filler textfiller text filler text filler textfiller text filler text filler textfiller text filler text filler textfiller text filler text filler textfiller text filler text filler textfiller text filler <br>text filler textfiller text filler text filler textfiller text filler text filler textfiller text filler text filler text
<pre>
sviluppatori:
(inserisci nome)
grafici:
(inserisci nome)
<pre>

{% endblock %}

app/templates/corsi/iscrizione.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
	<link rel="stylesheet" href="{% static 'css/iscrizione.css' %}">
{% endblock %}

{% block content %}

<div class="line"></div>

	<div class="pure-g">
		<div class="container">
			<div id="error"></div>

	    <div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2">titolo:<h1> {{ corso.nome }}</h1></div>
	    <div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2"><p>descrizione: {{corso.descrizione}}</p></div>
	    <div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2"><p>aula: {{corso.aula.nome_aula}}</p></div>
			<div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2"><p>Categoria: {{corso.categoria}}</p></div>
			<div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2"><p>Numero di iscritti: {{iscritti}}/{{corso.aula.capacita}}</p></div>
			{% if corso.progressivo == True %}
	    	<div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2"><p>progressivo: si</p></div>
			{% else %}
				<div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2"><p>singolo: si</p></div>
			{% endif %}
			<div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2"><p>creatore: {{corso.creatore.nome}}, {{corso.creatore.classe}}{{corso.creatore.sezione}}</p></div>
	    <div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-2 pure-u-xl-1-2">
			<button type="submit" class="btn btn-primary" onclick="iscrizione({{corso.id}}, this)">Iscriviti</button></div><br>

			<div class="pure-u-md-1-1 pure-u-sm-1-1 pure-u-1-1 pure-u-lg-1-1 pure-u-xl-1-1">Fasce:
				<div id="fasce">
					{% for fascia in fasce %}
						{{fascia}}|
					{% endfor %}
				</div>
				</div>
			</div><br>

	    <div class="line"></div>
	<script type="text/javascript">
		$(document).ready(function () {
		    var fasce = $('#fasce').html();
				var f_split = fasce.split("|");
				for (var f_counter in f_split) {
					f_split[f_counter] = f_split[f_counter].trim()
				}
				console.log(f_split)
				var response = "<table class='table'><thead><tr><th>#</th><th>L</th><th>Ma</th><th>Me</th><th>G</th><th>V</th></tr></thead>";
				var all_giorni = ["Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì"];
				var all_fasce = ["Prima Fascia", "Seconda Fascia", "Terza Fascia"];

				var table = {};
				for (g in all_giorni) {var fs = [];for (f in all_fasce) {fs.push(all_fasce[f]);}table[all_giorni[g]] = fs;}
				var table_formatted = [];
				for (var t in table) {for (var tr in table[t]) {table_formatted.push(t + ", " + table[t][tr]);}}

				for (var counter in table_formatted) {
					if (counter % 5 == 0) {
						response = response + '<tr><td>' + all_fasce[counter/5] + '</td>'
					}
					if (f_split.includes(table_formatted[counter])) {
						response += '<td class="centered-text">' + 'si' +'</td>'
					} else {
						response += '<td class="centered-text">' + 'no' +'</td>'
					}
					if (counter % 5 == 4) {
						response = response + '</tr>'
					}
				}
				$('#fasce').replaceWith(response + "</table>")
		});

	function getCookie(name) {var cookieValue = null;if (document.cookie && document.cookie != '') {var cookies = document.cookie.split(';');
	       for (var i = 0; i < cookies.length; i++) {var cookie = jQuery.trim(cookies[i]);if (cookie.substring(0, name.length + 1) == (name + '=')) {
	         cookieValue =   decodeURIComponent(cookie.substring(name.length + 1));break;}}}return cookieValue;}
	 var csrftoken = getCookie('csrftoken');function csrfSafeMethod(method) {return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));}

		function iscrizione(id_corso, btn) {

			var csrftoken = getCookie('csrftoken');
			$.ajax({

				beforeSend: function(xhr, settings) {
					if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
						xhr.setRequestHeader("X-CSRFToken", csrftoken);
					}
				},
				url: '/iscriviti/' + id_corso,
				data: {
					'id_corso': id_corso,
				},
				method: 'POST',
				datatype: 'json',
				success: function(r_d) {
					if (r_d['success']) {
						btn.innerHTML = 'iscrizione effettuata'
						window.location.replace("/success/"+id_corso);;}
					else {
						$('#error').addClass('alert')
						$('#error').addClass('alert-danger')
						$('#error').html(r_d['error']);
						btn.innerHTML = 'Iscriviti';
					}
				}
		});
		}
	</script>
{% endblock %}

app/templates/corsi/miei_corsi.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
    <table>
      <tr>
      {% if hosted_courses|length > 0 %}
        <h3>Corsi tenuti da te</h3><br>
      {% endif %}
      {% for corsi in hosted_courses %}
        {{corsi}}<br>
        <button class="btn btn-info"><a href="/dettagli/{{corsi.id}}">Vedi dettagli</a></button>
        <button class="btn btn-danger"><a href="/rimuovicorso/{{corsi.id}}">Elimina</a></button>
        <br><br>
      {% endfor %}
      <div class="line"></div>
      </tr>
      <tr>
        {% if iscrizioni|length > 0 %}
          <h3>Le tue iscrizioni</h3>
        {% endif %}
      </tr>
      <tr>
        {% for iscrizione in iscrizioni %}
          <br>
          fascia: {{iscrizione.fascia}}
          {% if iscrizione.empty == False %}
            <h6 id="{{iscrizione.id}}">Titolo: {{iscrizione.titolo}}</h6>
            <button type="button" name="button" class="btn btn-info"><a href="/dettagli/{{iscrizione.id}}">Vedi dettagli</a></button>
            <button class="btn btn-danger"><a href="/rimuovi/{{iscrizione.id}}">Rimuovi questa iscrizione</a></button>
            <br>
          {% else %}
            <p>questa fascia è vuota</p>
            <button class="btn btn-primary"><a href="/corsi/">Iscriviti a un corso</a></button><br>
          {% endif %}
        {% endfor %}
    </tr>

  </table>

  </div>

  <script type="text/javascript">
  $(document).ready(function () {
      $('#mieicorsi').toggleClass('active');
      $('#homelink').toggleClass('active');
  });
  </script>

{% endblock %}